
features = features = [
    "Total word count",
    "Sentence count",
    "Avg. word length",
    "Std. word length",
    "Type-token ratio",
    "Hapax legomena count",
    "Stopword ratio",
    "Punctuation ratio",
    "Noun ratio",
    "Verb ratio",
    "Adjective ratio",
    "Adverb ratio",
    "Pronoun ratio",
    "Avg. dependency depth",
    "Function word ratio",
    "Subordinate clause count",
    "Punctuation counts",
    "Sentence length variability",
    "Flesch–Kincaid readability",
    "Sentiment polarity",
    "Subjectivity",
    "Anger",
    "Joy",
    "Fear",
    "Sadness",
    "Disgust",
    "Surprise",
    "Certainty adverbs count",
    "Certainty verbs count",
    "Certainty adjectives count",
    "Doubt adverbs count",
    "Doubt verbs count",
    "Doubt adjectives count",
    "Hedges score",
    "Hedgehog C count",
    "Hedgehog D count",
    "Hedgehog E count",
    "Hedgehog I count",
    "Hedgehog N count",
    "C_ratio",
    "D_ratio",
    "E_ratio",
    "I_ratio",
    "N_ratio"
]

raw_features = {
    'word_count': 1,
    'sentence_count': 2,
    'avg_word_length': 3,
    'std_word_length': 4,
    'type_token_ratio': 5,
    'hapax_legomena': 6,
    'stopword_ratio': 7,
    'punctuation_density': 8,
    'noun_ratio': 9,
    'verb_ratio': 10,
    'adj_ratio': 11,
    'adv_ratio': 12,
    'pronoun_ratio': 13,
    'avg_dependency_depth': 14,
    'function_word_ratio': 15,
    'subordinate_clause_ratio': 16,
    'punctuation_usage': 17,
    'sentence_length_variation': 18,
    'readability_score': 19,
    'sentiment_polarity': 20,
    'sentiment_subjectivity': 21,
    'anger': 22,
    'joy': 23,
    'fear': 24,
    'sadness': 25,
    'disgust': 26,
    'surprise': 27,
    'certainty_adverbs_count': 28,
    'certainty_verbs_count': 29,
    'certainty_adjectives_count': 30,
    'doubt_adverbs_count': 31,
    'doubt_verbs_count': 32,
    'doubt_adjectives_count': 33,
    'hedges_score': 34,
    'hedge_C_count': 35,
    'hedge_D_count': 36,
    'hedge_E_count': 37,
    'hedge_I_count': 38,
    'hedge_N_count': 39,
    'C_ratio': 40,
    'D_ratio': 41,
    'E_ratio': 42,
    'I_ratio': 43,
    'N_ratio': 44
}

raw_feature_names = {
    'word_count': 'Total word count',
    'sentence_count': 'Sentence count',
    'avg_word_length': 'Avg. word length',
    'std_word_length': 'Std. word length',
    'type_token_ratio': 'Type-token ratio',
    'hapax_legomena': 'Hapax legomena count',
    'stopword_ratio': 'Stopword ratio',
    'punctuation_density': 'Punctuation density',
    'noun_ratio': 'Noun ratio',
    'verb_ratio': 'Verb ratio',
    'adj_ratio': 'Adjective ratio',
    'adv_ratio': 'Adverb ratio',
    'pronoun_ratio': 'Pronoun ratio',
    'avg_dependency_depth': 'Avg. dependency depth',
    'function_word_ratio': 'Function word ratio',
    'subordinate_clause_ratio': 'Subordinate clause count',
    'punctuation_usage': 'Punctuation counts',
    'sentence_length_variation': 'Sentence length variability',
    'readability_score': 'Flesch–Kincaid readability',
    'sentiment_polarity': 'Sentiment polarity',
    'sentiment_subjectivity': 'Subjectivity',
    'anger': 'Anger',
    'joy': 'Joy',
    'fear': 'Fear',
    'sadness': 'Sadness',
    'disgust': 'Disgust',
    'surprise': 'Surprise',
    'certainty_adverbs_count': 'Certainty adverbs count',
    'certainty_verbs_count': 'Certainty verbs count',
    'certainty_adjectives_count': 'Certainty adjectives count',
    'doubt_adverbs_count': 'Doubt adverbs count',
    'doubt_verbs_count': 'Doubt verbs count',
    'doubt_adjectives_count': 'Doubt adjectives count',
    'hedges_score': 'Hedges score',
    'hedge_C_count': 'Hedgehog C count',
    'hedge_D_count': 'Hedgehog D count',
    'hedge_E_count': 'Hedgehog E count',
    'hedge_I_count': 'Hedgehog I count',
    'hedge_N_count': 'Hedgehog N count',
    'C_ratio': 'C_ratio',
    'D_ratio': 'D_ratio',
    'E_ratio': 'E_ratio',
    'I_ratio': 'I_ratio',
    'N_ratio': 'N_ratio'
}